name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * *" # run at 5 AM UTC

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        renderer: [software, opengl]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      # This is only required for OpenGL builds on linux systems
      - name: Install OpenGL
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.renderer == 'opengl' }}
        uses: mstksg/get-package@v1
        with:
          apt-get: libmesa-dev


      - name: Run test suite
        run: zig build test

      - name: Compile game binaries
        run: zig build -Drenderer=${{ matrix.renderer }} install

      - name: Compile tool binaries
        run: zig build tools

      - name: Compile game assets
        run: zig build assets
