name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * *" # run at 5 AM UTC

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        renderer: [software, opengl, vulkan]
        embedded_resources: [false, true]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      # This is only required for linux systems that use pulseaudio/alsa
      - name: Install Audio Libraries
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: mstksg/get-package@v1
        with:
          apt-get: libpulse-dev libasound2-dev

      # This is only required for OpenGL and Vulkan builds on linux systems
      # TODO: Remove for vulkan when https://github.com/Aransentin/ZWL/issues/10 is implemented
      - name: Install OpenGL
        if: ${{ matrix.platform == 'ubuntu-latest' && (matrix.renderer == 'opengl' || matrix.renderer == 'vulkan') }}
        uses: mstksg/get-package@v1
        with:
          apt-get: mesa-common-dev libgl1-mesa-dev

      - name: Run test suite
        run: zig build test

      - name: Compile tool binaries
        run: zig build tools

      - name: Compile game assets
        run: zig build assets

      - name: Compile game binaries
        run: zig build -Dembed-resources=${{ matrix.embedded_resources }} -Drenderer=${{ matrix.renderer }} install
